version: "3"
services:
  lnd_bitcoin:
    image: lightningcn/lnd:v0.5.2-beta-amd64
    #image: btcpayserver/lnd:v0.5.1-beta-2
    container_name: lightningcn_lnd_bitcoin
    #restart: unless-stopped
    environment:
      LND_CHAIN: "btc"
      LND_ENVIRONMENT: ${BITCOIN_NETWORK:-regtest}
      LND_DATA: /data
      #LND_BITCOIND: /btcdata
      LND_EXTRA_ARGS: |
        restlisten=0.0.0.0:8080
        rpclisten=127.0.0.1:10008
        rpclisten=0.0.0.0:10009
        bitcoin.node=bitcoind
        bitcoind.rpchost=${BITCOIN_NODE:-127.0.0.1}:8332
        bitcoind.zmqpubrawblock=tcp://${BITCOIN_NODE:-127.0.0.1}:28332
        bitcoind.zmqpubrawtx=tcp://${BITCOIN_NODE:-127.0.0.1}:28333
        externalip=${LIGHTNING_HOST}:9735
        alias=${LIGHTNING_ALIAS}
        #bitcoind.rpcuser=Removed
        #bitcoind.rpcpass=Removed
        #adminmacaroonpath=/data/admin.macaroon
        #invoicemacaroonpath=/data/invoice.macaroon
        #readonlymacaroonpath=/data/readonly.macaroon
        autopilot.active=1
        autopilot.maxchannels=50
        autopilot.allocation=0.8
        autopilot.minconfs=6
        noseedbackup=1
        notls=1
    volumes:
        - ./lnd_data:/data
        - ~/.bitcoin:/root/.bitcoin
    ports:
        - "9735:9735"
        - "2222:22"
    expose:
      - "8080"
      - "9735"
    network_mode: host  #only for support local rpc 127.0.0.1

  rtl:
    #restart: unless-stopped
    image: shahanafarooqui/rtl:0.2.6-amd64 
    container_name: lightningcn_rtl-wallet
    environment:
      LND_SERVER_URL: http://lnd_bitcoin:8080/v1
      MACAROON_PATH: "/root/.lnd/data/chain/bitcoin/${BITCOIN_NETWORK:-regtest}"
      LND_CONFIG_PATH: /root/.lnd/lnd.conf
      BITCOIND_CONFIG_PATH: /root/.bitcoin/bitcoin.conf
      NODE_AUTH_TYPE: CUSTOM
      RTL_CONFIG_PATH: /data/RTL.conf
      #RTL_SSO: 0
      #RTL_COOKIE_PATH: /data/.cookie
      #LOGOUT_REDIRECT_LINK: /logout
    ports:
        - "3000:3000"
    volumes:
        - ./rtldata:/data
        - ./lnd_data:/root/.lnd
        - ~/.bitcoin:/root/.bitcoin
    links:
      - lnd_bitcoin
    depends_on:
        - "lnd_bitcoin"
